//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarmingAssistant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Article
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Article()
        {
            this.ArticleComments = new HashSet<ArticleComment>();
        }
    
        public int id { get; set; }
        [Required(ErrorMessage ="Please Give Title")]
        [Display(Name ="Title")]
        [StringLength(maximumLength:200,MinimumLength =3)]
        public string title { get; set; }
        [Required(ErrorMessage = "Please Give Title")]
        [Display(Name = "Body")]
        [DataType(DataType.MultilineText)]
        [StringLength(maximumLength: 4000, MinimumLength = 3)]
        public string body { get; set; }
        [Display(Name ="Publish Date")]
        public Nullable<System.DateTime> publishDate { get; set; }
        [Required]
        [Display(Name ="Product Name")]
        public Nullable<int> productId { get; set; }
    
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
    }
}
