//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarmingAssistant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ArticleComment
    {
        public int id { get; set; }
        public Nullable<int> articleId { get; set; }
        [Required]
        [Display(Name ="User Name")]
        public Nullable<int> userId { get; set; }
        public string comment { get; set; }
        public Nullable<System.DateTime> commentDate { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual User User { get; set; }
    }
}
