//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarmingAssistant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class PaymentMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PaymentMethod()
        {
            this.Orders = new HashSet<Order>();
        }
    
        public int id { get; set; }
        [Required]
        [Display(Name = "Name")]
        [StringLength(maximumLength: 35, MinimumLength = 3)]
        public string name { get; set; }
        [Required]
        [Display(Name = "Description")]
        [StringLength(maximumLength: 35, MinimumLength = 3)]
        public string description { get; set; }
        
        [Display(Name = "Processor")]
        
        public string processor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
