//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarmingAssistant.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductStock
    {
        public int id { get; set; }
        public int productId { get; set; }
        public int inQuantity { get; set; }
        public int outQuantity { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
