//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartFarmingAssistant.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.ProductComments = new HashSet<ProductComment>();
            this.Orders = new HashSet<Order>();
            this.wishlists = new HashSet<wishlist>();
            this.ArticleComments = new HashSet<ArticleComment>();
        }
    
        public int id { get; set; }
        [Required]
        [Display(Name = "Customer")]
        [StringLength(maximumLength: 35, MinimumLength = 3)]
        public string name { get; set; }
        [Required]
        [Display(Name = "Phone")]
        [StringLength(maximumLength: 35, MinimumLength = 3)]
        [DataType(DataType.PhoneNumber)]
        public string contact { get; set; }
        [Required]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "The email address is not valid")]
        public string email { get; set; }
        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [StringLength(maximumLength: 35, MinimumLength = 3)]
        public string password { get; set; }
        
        [Display(Name = "Date")]
        
        public Nullable<System.DateTime> createDate { get; set; }
        [Required]
        [Display(Name = "Gender")]
        
        public int genderId { get; set; }
        
        [Display(Name = "Type")]
        
        public string type { get; set; }
        [Required]
        [Display(Name = "Address")]
        [StringLength(maximumLength: 35, MinimumLength = 3)]
        public string address { get; set; }
        [Required]
        [Display(Name = "City")]
       
        public int cityId { get; set; }
    
        public virtual City City { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductComment> ProductComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wishlist> wishlists { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleComment> ArticleComments { get; set; }
    }
}
