//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LimonSelling.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductImage
    {
        public int id { get; set; }
        [Required]
        public int productId { get; set; }
        [Display(Name ="Image")]
       
        public string image1 { get; set; }
        [Required]
        [Display(Name ="Title")]
        public string title { get; set; }
        [Display(Name ="Date")]
        public Nullable<System.DateTime> createDate { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
